CREATE TABLE IF NOT EXISTS `questions` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(1024) NOT NULL,
  `description` TEXT NOT NULL,
  `difficulty` VARCHAR(32) NOT NULL,
  `category` VARCHAR(128),
  `input_format` TEXT,
  `output_format` TEXT,
  `constraints` TEXT,
  `sample_input` TEXT,
  `sample_output` TEXT,
  `tags` VARCHAR(1024),
  `starter_code_json` TEXT,
  `time_complexity` VARCHAR(128),
  `space_complexity` VARCHAR(128),
  `test_cases_json` TEXT,
  `acceptance` DOUBLE DEFAULT 0,
  `likes` INT DEFAULT 0,
  `dislikes` INT DEFAULT 0,
  `company_tags` VARCHAR(1024),
  `premium` BOOLEAN DEFAULT FALSE,
  `frequency_level` VARCHAR(64),
  `contest_origin` VARCHAR(128)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
